apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "89.2.2"
    helm:
      values: |
        grafana:
          adminPassword: "homelabgrafana"
          ingress:
            enabled: false
          service:
            type: NodePort
            nodePort: 30030
          persistence:
            enabled: true
            storageClassName: longhorn
            size: 5Gi
          grafana.ini:
            server:
              root_url: "http://192.168.6.17:30030"

        prometheus:
          service:
            type: NodePort
            nodePort: 30090
          prometheusSpec:
            retention: 30d
            externalUrl: "http://192.168.6.17:30090"
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
              limits:
                memory: 2Gi
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 20Gi

        alertmanager:
          service:
            type: NodePort
            nodePort: 30093
          alertmanagerSpec:
            externalUrl: "http://192.168.6.17:30093"
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi

        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false
        kubeEtcd:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
