apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmp-exporter
  template:
    metadata:
      labels:
        app: snmp-exporter
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-elitedesk-1
      containers:
      - name: snmp-exporter
        image: prom/snmp-exporter:latest
        ports:
        - containerPort: 9116
---
apiVersion: v1
kind: Service
metadata:
  name: snmp-exporter
  namespace: monitoring
spec:
  selector:
    app: snmp-exporter
  ports:
  - port: 9116
    targetPort: 9116
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: snmp-ups
  namespace: monitoring
  labels:
    release: kube-prom
spec:
  endpoints:
  - port: http
    path: /snmp
    params:
      module: [if_mib]
      target: ["192.168.6.111"]
    relabelings:
    - sourceLabels: [__param_target]
      targetLabel: instance
    - targetLabel: __address__
      replacement: snmp-exporter:9116
  selector:
    matchLabels:
      app: snmp-exporter
